jcrew_app/config/routes.rb
Rails.application.routes.draw do

  root 'main#home'

  get '/team' => 'main#team', as: :team

  get '/users/edit/:id' => 'account#edit', as: :user_edit
  get '/users/:id' => 'account#show', as: :user
  post '/users/edit/:id' => 'account#update', as: :user_update

  get '/blog' => 'blog#index', as: :posts
  post '/blog' => 'blog#list', as: :filter_posts
  get '/blog/post/:id' => 'blog#show', as: :post
  get '/blog/new' => 'blog#new', as: :new_post
  get '/blog/edit/:id' => 'blog#edit', as: :edit_post
  post '/blog/edit/:id' => 'blog#update', as: :update_post
  post '/blog/new' => 'blog#create', as: :create_post
  delete '/blog/post/:id'=> 'blog#destroy', as: :delete_post

  post '/blog/post/comment/:id' => 'comments#create', as: :post_comment
  post '/blog/post/reply/comment/:post_id/:comment_id' => 'reply#create', as: :post_reply
  delete '/blog/post/comment/:id' => 'comments#destroy', as: :delete_comment

  get '/blog/category' => 'category#index', as: :categories
  post '/blog/category/create' => 'category#create', as: :create_category
  post '/blog/category/:id/update' => 'category#update', as: :update_category
  delete '/blog/category/:id/delete' => 'category#destroy', as: :delete_category

  get '/register' => 'session#register', as: :register
  post '/register' => 'session#register_user', as: :register_user
  get '/login' => 'session#login', as: :login
  post '/login' => 'session#login_user', as: :login_user
  delete '/logout' => 'session#logout', as: :logout

end

jcrew_app/app/models/category.rb
class Category < ActiveRecord::Base

	# DO NOT ALTER ANYTHING BELOW THIS LINE
	
	has_many :categories_posts, class_name: "CategoryPost", foreign_key: "category_id"
	has_many :posts, through: :categories_posts, source: :post
end

jcrew_app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout false

  def index
    @categories = Category.all
  end

  def new
    # @subject = Category.new({:name => "Default"})
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(:action => 'index', :id => @category.id)
    else
      render('edit')
    end
  end

  def delete
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.destroy(params[:id])
    redirect_to(:action => 'index')
  end


  private

    def category_params
      params.require(:category).permit(:name)
    end

end

jcrew_app/app/controllers/category_controller.rb
class CategoryController < ApplicationController
	before_action :redirect_non_admins

	def index
		@categories = Category.all
	end

	def create
		Category.create(:name => params[:category][:name])
		redirect_to :back
	end

	def update
		Category.update(params[:id], :name => params[:category][:name])
		redirect_to :back
	end

	def destroy
		Category.destroy(params[:id])
		redirect_to :back
	end

end

jcrew_app/app/helpers/categories_helper.rb
module CategoriesHelper
end

jcrew_app/app/helpers/category_helper.rb
module CategoryHelper
end

jcrew_app/app/views/category/index.html.erb
<!-- CATEGORY PAGE -->

<div class="categories-div">
    <h3 id="container-meet">Categories</h1><br><br>
    <% categories = Category.all %>
    <% categories.each do |category| %>
        <%= form_for :category, :url => update_category_path(category.id) do |f| %>
            <!-- <font style="margin-right: 0.5em"><%= "#{category.name}" %></font> -->
            <%= f.text_field :name, :value => category.name, placeholder: "Rename category", class: "signature-textarea", style: "color: white;font-size:16px;width:40%;color:black" %>
            <%= link_to 'Delete', delete_category_path(category.id), class: "delete-post", style: "color:white;float:right;text-align:center", method: :delete %>
            <br><br>
        <% end %>
        <br><br>
    <% end %>
    <%= form_for :category, :url => create_category_path do |c| %>
        <%= c.text_field :name, placeholder: 'Enter category name', class: "signature-textarea", style: "color: white;font-size:16px;width:40%;color:black" %>
    <% end %>
        
</div>