jcrew_app/config/routes.rb
Rails.application.routes.draw do

  root 'main#home'

  get '/team' => 'main#team', as: :team

  get '/users/edit/:id' => 'account#edit', as: :user_edit
  get '/users/:id' => 'account#show', as: :user
  post '/users/edit/:id' => 'account#update', as: :user_update

  get '/blog' => 'blog#index', as: :posts
  post '/blog' => 'blog#list', as: :filter_posts
  get '/blog/post/:id' => 'blog#show', as: :post
  get '/blog/new' => 'blog#new', as: :new_post
  get '/blog/edit/:id' => 'blog#edit', as: :edit_post
  post '/blog/edit/:id' => 'blog#update', as: :update_post
  post '/blog/new' => 'blog#create', as: :create_post
  delete '/blog/post/:id'=> 'blog#destroy', as: :delete_post

  post '/blog/post/comment/:id' => 'comments#create', as: :post_comment
  post '/blog/post/reply/comment/:post_id/:comment_id' => 'reply#create', as: :post_reply
  delete '/blog/post/comment/:id' => 'comments#destroy', as: :delete_comment

  get '/blog/category' => 'category#index', as: :categories
  post '/blog/category/create' => 'category#create', as: :create_category
  post '/blog/category/:id/update' => 'category#update', as: :update_category
  delete '/blog/category/:id/delete' => 'category#destroy', as: :delete_category

  get '/register' => 'session#register', as: :register
  post '/register' => 'session#register_user', as: :register_user
  get '/login' => 'session#login', as: :login
  post '/login' => 'session#login_user', as: :login_user
  delete '/logout' => 'session#logout', as: :logout

end

jcrew_app/app/views/layouts/_post.html.erb
<div style="height: auto;overflow: hidden;padding: 10px;margin-bottom: 2em;background-color: white;z-index: 10;">
    <div class="post-info" style="text-align: center">
    	<% if index %>
	        <%= link_to "#{post.title}", post_path(post.id), :id => "post-title" %>
        <% else %>
        	<p id="post-title"><%= "#{post.title}" %></p>
        <% end %>
        <br>
        <br>
        <% date = post.updated_at.to_time.strftime('%B %e at %l:%M %p') %>
        <p id="post-date-member"><%= "#{date} by #{User.find(post.user_id).name}" %></p>
        <br>
        <%count = post.comments.count%>
        <%string = pluralize(count, 'comment')%>
        <p id="post-comments"> <%= "#{string}" %> </p>
        <% if post.created_at != post.updated_at %>
            <p id="post-comments" style="font-size: 12px; width: 20%;margin-top: 0.3em"> <%= "Edited" %> </p>
        <% end %>
        <br>
        <!-- <div class="g-plus" data-action="share" data-annotation="bubble" data-href=<%= "http://www.facebook.com#{post_path(post.id)}" %>></div>
        <br>
        <br>
        <div class="fb-share-button" data-href=<%= "http://www.facebook.com#{post_path(post.id)}" %> data-layout="button_count"></div> -->
        <% categories = post.categories %>
        <% categories.each do |category| %>
            <p id="post-comments" style="font-size: 12px; width: auto;max-width: 50%;margin-top: 0.3em"> <%= "#{category.name}" %> </p>
        <% end %>
    </div>

    <div class="post-content">
        <!-- <% content = post.content + "<br><br> <i>#{post.user.signature}</i>" if not post.user.signature.blank? %>
        <% content = post.content if post.user.signature.blank? %> -->
        <%= post.content_html + "#{post.user.signature}" if not post.user.signature.blank?%>
        <%= post.content_html if post.user.signature.blank? %>
        <!-- <%= simple_format(content) %> -->
    </div>
</div>

jcrew_app/app/views/layouts/_post_edit.html.erb
<% if flash[:warning] && flash[:warning].count > 0 %>
    <div class="warning"><%= safe_join(flash[:warning], "<br>".html_safe) %></div>
    <br>
<% end %>
<div class="warning">You can use HTML tags in the post content</div>

<!-- operation variable is passed when rendering this partial :operation => "OPERATION" -->
<% if operation == "edit" %>
    <%= form_for :post, :url => update_post_path(params[:id]) do |f| %>
        <%= f.text_field :title, :value => @post.title, class: "login-input", placeholder: "Enter post title", style: "margin-top: 1em;" %>
         <%= f.text_area :content, :value => @post.content, class: "signature-textarea", placeholder: "Enter post content", style: "margin-top: 1em; width: 100%; max-width: 100%;", :rows => 18 %>
         <!-- Select a category -->
         <div class="categories-div">
            <h3 id="container-meet">Categories</h1><br><br>
            <%= fields_for :category do |c| %>
                <% categories = Category.all %>
                <% categories.each do |category| %>
                    <%= c.check_box category.id, {:checked => CategoryPost.exists?(:post_id => params[:id], :category_id => category.id)} %>
                    <font style="margin-right: 0.5em"><%= "#{category.name}" %></font>
                <% end %>
            <% end%>
         </div>
         <%= f.submit "Save", class: "login-button", style: "margin-top: 0.5em;" %>
    <% end %>
<% else %>
    <%= form_for :post, :url => create_post_path do |f| %>
        <%= f.text_field :title, class: "login-input", placeholder: "Enter post title", style: "margin-top: 1em;" %>
        <%= f.text_area :content, class: "signature-textarea", placeholder: "Enter post content", style: "margin-top: 1em; width: 100%; max-width: 100%;", :rows => 18 %>
        <div class="categories-div">
            <h3 id="container-meet">Categories</h1><br><br>
            <%= fields_for :category do |c| %>
                <% categories = Category.all %>
                <% categories.each do |category| %>
                    <%= c.check_box category.id, {:checked => CategoryPost.exists?(:post_id => params[:id], :category_id => category.id)} %>
                    <font style="margin-right: 0.5em"><%= "#{category.name}" %></font>
                <% end %>
            <% end%>
         </div>
        <%= f.submit "Add", class: "login-button", style: "margin-top: 0.5em;" %>
    <% end %>
<% end %>

jcrew_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jcrew</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
	<div style="float: left;width: 40%;height: 55%;position:relative;left:5em;border: 0px solid rgba(208, 208, 208, 0.67);position: relative;top:25%;">
		<%= link_to "Jcrew", root_path, class: "crew-logo", style: "float: left" %>
	</div>
	<div style="float:right;height: 100%;right: 15em;position:relative">
		<ul class="navbar-links">
			<li style="float: left">
				<%= link_to "Home", root_path, class: "navbar-link" %>
			</li>
			<li style="float: left">
				<%= link_to "Blog", "/blog", class: "navbar-link" %>
			</li>
			<li style="float: left" id="test">
				<%= link_to "Team", "/team", class: "navbar-link" %>
			</li>
			<li style="float: left">
				<!-- <p class="navbar-link" id="user">Me</p> -->
				<% if logged_in? %>
					<p class="navbar-link" id="user"><%= @current_user.name %></p>
				<% else %>
					<!-- <p class="navbar-link" id="user">Log in</p> -->
					<%= link_to "Log in", login_path, class: "navbar-link" %>
				<% end %>
			</li>
		</ul>

		<% if logged_in? %>
			<div class="account-menu-div display-none">
				<table class="account-menu">
					<% if @current_user.is_admin %>
						<tr class="account-menu-item">
							<td><%= link_to "Add Blog Post", new_post_path %></td>
						</tr>
						<tr class="account-menu-item">
							<td><%= link_to "Post Categories", categories_path %></td>
						</tr>
					<% end %>
					<tr class="account-menu-item">
						<td><%= link_to "Profile", user_path(@current_user.id) %></td>
					</tr>
					<tr class="account-menu-item">
						<td><%= link_to "Log out", logout_path, method: :delete %></td>
					</tr>
				</table>
			</div>
		<% end %>
		</div>

</div>

<div class="container-body">
	<% if ['/login', '/register'].include? request.path %>
		<canvas id="canvas"></canvas>
	<% end %>
  <br><br><br>
  <div class="container-container" style="padding: 0px;background-color: transparent;">
		<%= yield %>
	</div>
</div>

</body>
</html>