jcrew_app/config/routes.rb
Rails.application.routes.draw do

  root 'main#home'

  get '/team' => 'main#team', as: :team

  get '/users/edit/:id' => 'account#edit', as: :user_edit
  get '/users/:id' => 'account#show', as: :user
  post '/users/edit/:id' => 'account#update', as: :user_update

  get '/blog' => 'blog#index', as: :posts
  post '/blog' => 'blog#list', as: :filter_posts
  get '/blog/post/:id' => 'blog#show', as: :post
  get '/blog/new' => 'blog#new', as: :new_post
  get '/blog/edit/:id' => 'blog#edit', as: :edit_post
  post '/blog/edit/:id' => 'blog#update', as: :update_post
  post '/blog/new' => 'blog#create', as: :create_post
  delete '/blog/post/:id'=> 'blog#destroy', as: :delete_post

  post '/blog/post/comment/:id' => 'comments#create', as: :post_comment
  post '/blog/post/reply/comment/:post_id/:comment_id' => 'reply#create', as: :post_reply
  delete '/blog/post/comment/:id' => 'comments#destroy', as: :delete_comment

  get '/blog/category' => 'category#index', as: :categories
  post '/blog/category/create' => 'category#create', as: :create_category
  post '/blog/category/:id/update' => 'category#update', as: :update_category
  delete '/blog/category/:id/delete' => 'category#destroy', as: :delete_category

  get '/register' => 'session#register', as: :register
  post '/register' => 'session#register_user', as: :register_user
  get '/login' => 'session#login', as: :login
  post '/login' => 'session#login_user', as: :login_user
  delete '/logout' => 'session#logout', as: :logout

end

jcrew_app/app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
		@posts = Post.all.order('updated_at DESC')
	end

	def list
		# puts "PARAMS #{params}"
		hash = params[:category]
		selected_categories_array = []
		hash.each{ |k,v|
			if v == 1 || v == '1'
				selected_categories_array << k
			end
		}
		categories = Category.where(:id => selected_categories_array)
		@posts = []
		categories.each{ |category|
			@posts << category.posts.order('updated_at DESC')
		}
		@posts.to_a.flatten!.sort!{|a,b| b.updated_at <=> a.updated_at}
		@posts = @posts.uniq
		render 'index'
	end

	def show
		# redirect_not_published
		@post = Post.find(params[:id])
	end

	def new
		redirect_guests
	end

	def create
		hash = params[:post]
		@post = Post.create(:title => hash[:title], :content => hash[:content], :user_id => @current_user.id)
		if params[:category] != nil
			categories = params[:category]
			selected_categories_array = []
			categories.each{ |k,v|
				if v == 1 || v == '1'
					selected_categories_array << k
				end
			}
			ActiveRecord::Base.transaction do
				selected_categories_array.each {|k| 
					CategoryPost.create(:post_id => @post.id, :category_id => k) if not CategoryPost.exists?(:post_id => @post.id, :category_id => k)
				}
			end
		end

		flash[:warning] = []
		flash[:warning] << "Title cannot be left blank" if hash[:title].blank?
		flash[:warning] << "Content cannot be left blank" if hash[:content].blank?
		redirect_to new_post_path and return if flash[:warning].count > 0
		redirect_to post_path(@post.id)
	end

	def edit
		redirect_guests
		@post = Post.find(params[:id])
	end

	def update
		hash = params[:post]
		if params[:category] != nil
			categories = params[:category]
			selected_categories_array = []
			removed_categores_array = []
			categories.each{ |k,v|
				if v == 1 || v == '1'
					selected_categories_array << k
				elsif v == 0 || v == '0'
					removed_categores_array << k
				end
			}

			CategoryPost.where(:post_id => params[:id], :category_id => removed_categores_array).delete_all
			ActiveRecord::Base.transaction do
			  selected_categories_array.each {|k| 
			  	CategoryPost.create(:post_id => params[:id], :category_id => k) if not CategoryPost.exists?(:post_id => params[:id], :category_id => k)
			   }
			end
		end

		flash[:warning] = []
		flash[:warning] << "Title cannot be left blank" if hash[:title].blank?
		flash[:warning] << "Content cannot be left blank" if hash[:content].blank?
		redirect_to edit_post_path and return if flash[:warning].count > 0
		Post.find(params[:id]).update(:title => hash[:title], :content => hash[:content])
		redirect_to post_path(params[:id])
	end

	def destroy
		Post.delete(params[:id])
		redirect_to posts_path
	end
end

jcrew_app/app/helpers/blog_helper.rb
module BlogHelper
end

jcrew_app/app/views/blog/edit.html.erb
<!-- POST PAGE -->

<%= render '/layouts/post_edit', :operation => "edit" %>

<!-- if false here acts as a block comment; the whole code inside it will not be executed -->
<% if false %>
    <% if flash[:warning] && flash[:warning].count > 0 %>
    <div class="warning"><%= safe_join(flash[:warning], "<br>".html_safe) %></div>
    <br>
    <% end %>
    <div class="warning">You can use HTML tags in the post content</div>
<% end %>

<% if false %>
	<%= form_for :post, :url => update_post_path(params[:id]) do |f| %>
	    <%= f.text_field :title, :value => @post.title, class: "login-input", placeholder: "Enter post title", style: "margin-top: 1em;" %>
	     <%= f.text_area :content, :value => @post.content, class: "signature-textarea", placeholder: "Enter post content", style: "margin-top: 1em; width: 100%; max-width: 100%;", :rows => 18 %>
	     <%= f.submit "Save", class: "login-button", style: "margin-top: 1em;" %>
	<% end %>
<% end %>

jcrew_app/app/views/blog/index.html.erb
<!-- BLOG PAGE -->
<!-- <button type="button" class="list-posts">Add Post</button> -->
<!-- <span><%# button_to "Add Post", new_post_path(params[:id]), class: "list-posts", method: :get %></span> -->
<% if Category.count > 0 && Post.count > 0 %>
    <div class="categories-div" style="width: 100%;display: none">
        <h3 id="container-meet">Filter by Categories</h1><br><br>
        <%= form_for :category, :url => filter_posts_path do |f| %>
            <% categories = Category.all %>
            <% categories.each do |category| %>
                <%= f.check_box category.id, {:checked => CategoryPost.exists?(:post_id => params[:id], :category_id => category.id)} %>
                <font style="margin-right: 0.5em"><%= "#{category.name}" %></font>
            <% end %>
            <%= f.submit 'Filter', class: "list-posts", style: "float: right;color: white" %>
        <% end %>
    </div>
     <br>
    <button type="button" class="list-posts" id="list-posts" style="float: right">Filter Posts</button>
<% end %>
<br><br>
<div style="position: relative;z-index: 2">
    <% @posts.each do |post| %>
<!--     <div style="height: auto;overflow: hidden;padding: 10px;margin-bottom: 2em">
        <div class="post-info" style="text-align: center">
            <%= link_to "#{post.title}", post_path(post.id), :id => "post-title" %>
            <br>
            <br>
            <% date = post.updated_at.to_time.strftime('%B %e at %l:%M %p') %>
            <p id="post-date-member"><%= "#{date} by #{User.find(post.user_id).name}" %></p>
            <br>
            <%count = post.comments.count%>
            <%string = pluralize(count, 'comment')%>
            <p id="post-comments"> <%= "#{string}" %> </p>
            <% if post.created_at != post.updated_at %>
                <p id="post-comments" style="font-size: 12px; width: 20%;margin-top: 0.3em"> <%= "Edited" %> </p>
            <% end %>
        </div>
        <div class="post-content">
            <% content = post.content + "<br><br> #{User.first.signature}" if not User.first.signature.blank? %>
            <% content = post.content if User.first.signature.blank? %>
            <%= simple_format(content) %>
        </div>
    </div> -->

    <!-- This following line replaced the whole commented div block before it. It is called a partial -->
    <%= render '/layouts/post', :post => post, :index => true %>
<% end %>
</div>

<style type="text/css">
    .box{
        z-index: 1;
        top: 11em;
        position: fixed;
        width: 100;
    }
</style>

jcrew_app/app/views/blog/new.html.erb
<!-- POST PAGE -->

<%= render '/layouts/post_edit', :operation => "add" %>

<!-- if false here acts as a block comment; the whole code inside it will not be executed -->
<% if false %>
    <% if flash[:warning] && flash[:warning].count > 0 %>
    <div class="warning"><%= safe_join(flash[:warning], "<br>".html_safe) %></div>
    <br>
    <% end %>
    <div class="warning">You can use HTML tags in the post content</div>
<% end %>

<% if false %>
    <%= form_for :post, :url => create_post_path do |f| %>
        <%= f.text_field :title, class: "login-input", placeholder: "Enter post title", style: "margin-top: 1em;" %>
        <%= f.text_area :content, class: "signature-textarea", placeholder: "Enter post content", style: "margin-top: 1em; width: 100%; max-width: 100%;", :rows => 18 %>
        <br>
        <%= f.submit "Add", class: "login-button", style: "margin-top: 2em;" %>
    <% end %>
<% end %>

jcrew_app/app/views/blog/show.html.erb
<!-- POST PAGE -->
<% if logged_in? && @current_user.is_admin %>
    <div style="display:inline;">
        <button type="button" class="delete-post ask-delete" style="float:right">Delete Post</button>
        <%= button_to "Edit Post", edit_post_path(@post.id), class: "delete-post", style: "float:right;margin-right: 1em;", method: :get %>
    </div>
<% end %>

<br><br>
<!-- <div style="height: auto;overflow: hidden;margin-bottom: 5em">
    <div class="post-info" style="text-align: center">
        <p id="post-title"><%= "#{@post.title}" %></p>
        <br>
        <% date = @post.updated_at.to_time.strftime('%B %e at %l:%M %p') %>
        <p id="post-date-member"><%= "#{date} by #{User.find(@post.user_id).name}" %></p>
        <br>
            <%count = @post.comments.count%>
            <%string = pluralize(count, 'comment')%>
            <p id="post-comments"> <%= "#{string}" %> </p>
        <% if @post.created_at != @post.updated_at %>
            <p id="post-comments" style="font-size: 12px; width: 20%;margin-top: 0.3em"> <%= "Edited" %> </p>
        <% end %>
    </div>
    <div class="post-content">
        <% content = @post.content + "<br><br> #{User.first.signature}" if not User.first.signature.blank? %>
        <% content = @post.content if User.first.signature.blank? %>
        <%= simple_format(content) %>
    </div>
</div> -->

<!-- This following line replaced the whole commented div block before it. It is called a partial -->
<%= render '/layouts/post', :post => @post, :index => false %>

<%= render_shareable :buttons => ['twitter'] %>
<%= render_shareable :buttons => ['facebook'] %>
<%= render_shareable :buttons => ['google_plus'] %>

<%def body_html
auto_html(self[:content_html]) { simple_format; link(:target => 'blank') }
end%>

<% comments = @post.comments %>
<div class="post-comments">
    <h3 id="container-meet">Comments</h1>
    <% if logged_in? %>
        <%= form_for :comment, :url => post_comment_path do |f| %>
            <%= f.text_field :content, class: "comment_input", placeholder: "Add a new comment", style: "float:left;margin-bottom: 1em" %>
        <% end %>
    <% end %>
    <% comments.each do |comment| %>
        <% if comment.comment.count == 0 %>
                <div class="post-comment">
                    <strong><span><%= "#{comment.user.name}" %></span></strong><span><%= link_to 'Delete', delete_comment_path(comment.id), class: "delete-post", style: "color:white;float:right;text-align:center", method: :delete if logged_in? && (@current_user.is_admin || comment.user_id == @current_user.id)%></span>
                    <br>
                    <!-- <% content = comment.content_html + "<br><br> <i>#{comment.user.signature}</i>" if not comment.user.signature.blank? %>
                    <% content = comment.content_html if comment.user.signature.blank? %> -->
                    <%= comment.content_html + "#{comment.user.signature}" if not comment.user.signature.blank?%>
                    <%= comment.content_html if comment.user.signature.blank? %>
                    <!-- <p style="word-wrap: break-word"><%= simple_format(content) %></p> -->
                    <hr style="margin-top: 0.4em; border-color: rgba(255, 30, 30, 0.65);; border-width: 1px"></hr>
                    <br>
                    <% replies = comment.replies %>
                    <% replies.each do |reply| %>
                        <div class="comment-reply" style="margin-bottom: 1em">
                            <strong><span><%= "#{reply.user.name}" %></span></strong><span><%= link_to 'Delete', delete_comment_path(reply.id), class: "delete-post", style: "color:white;float:right;text-align:center", method: :delete if logged_in? && (@current_user.is_admin || comment.user_id == @current_user.id)%></span>
                            <br>
                            <!-- <% content = reply.content_html + "<br><br> <i>#{comment.user.signature}</i>" if not comment.user.signature.blank? %>
                            <% content = reply.content_html if comment.user.signature.blank? %> -->
                            <%= reply.content_html + "#{comment.user.signature}" if not comment.user.signature.blank?%>
                            <%= reply.content_html if comment.user.signature.blank? %>
                            <!-- <p style="word-wrap: break-word"><%= simple_format(content) %></p> -->
                        </div>
                    <% end %>
                    <% if logged_in? %>
                        <%= form_for :reply, :url => post_reply_path(@post.id,comment.id) do |r| %>
                            <%= r.text_field :content, class: "reply_input", placeholder: "Reply to this comment", style: "margin-top: 1em;" %>
                         <br>
                        <% end %>
                    <% end %>
                </div>   
        <% end %>
    <% end %>
</div>

<!-- Delete Post Alert Box -->

<div class="dimmer display-none">
    <div class="alert-view">
        <p>Are you sure?</p>
        <div style="top: 30%; position: relative;width: 100%;">
            <%= button_to "Yes", delete_post_path(params[:id]), class: "delete-post", style: "width: 40%", method: :delete %>
            <%# button_to "Cancel", edit_post_path(params[:id]), class: "delete-post", style: "width: 40%", method: :get %>
            <button type="button" class="delete-post cancel-delete" style="width: 40%">Cancel</button>
        </div>
    </div>
</div>