jcrew_app/config/routes.rb
Rails.application.routes.draw do

  root 'main#home'

  get '/team' => 'main#team', as: :team

  get '/users/edit/:id' => 'account#edit', as: :user_edit
  get '/users/:id' => 'account#show', as: :user
  post '/users/edit/:id' => 'account#update', as: :user_update

  get '/blog' => 'blog#index', as: :posts
  post '/blog' => 'blog#list', as: :filter_posts
  get '/blog/post/:id' => 'blog#show', as: :post
  get '/blog/new' => 'blog#new', as: :new_post
  get '/blog/edit/:id' => 'blog#edit', as: :edit_post
  post '/blog/edit/:id' => 'blog#update', as: :update_post
  post '/blog/new' => 'blog#create', as: :create_post
  delete '/blog/post/:id'=> 'blog#destroy', as: :delete_post

  post '/blog/post/comment/:id' => 'comments#create', as: :post_comment
  post '/blog/post/reply/comment/:post_id/:comment_id' => 'reply#create', as: :post_reply
  delete '/blog/post/comment/:id' => 'comments#destroy', as: :delete_comment

  get '/blog/category' => 'category#index', as: :categories
  post '/blog/category/create' => 'category#create', as: :create_category
  post '/blog/category/:id/update' => 'category#update', as: :update_category
  delete '/blog/category/:id/delete' => 'category#destroy', as: :delete_category

  get '/register' => 'session#register', as: :register
  post '/register' => 'session#register_user', as: :register_user
  get '/login' => 'session#login', as: :login
  post '/login' => 'session#login_user', as: :login_user
  delete '/logout' => 'session#logout', as: :logout

end

jcrew_app/app/controllers/session_controller.rb
class SessionController < ApplicationController

	def register
		@user = User.new
	end

	def register_user
		hash = params[:register]
		@user = User.new(:email => hash[:email], :name => hash[:name], :password => hash[:password])
    if @user.save
      log_in @user
      redirect_to posts_path
    else
      render 'register'
    end
	end

	def login
	end

	def login_user
		hash = params[:login]
		user = User.find_by_email(hash[:email])
		if user && user.authenticate(hash[:password])
			log_in user
			redirect_to posts_path
		else
			flash[:warning] = ["Wrong credentials"]
			render 'login'
		end
	end

	def logout
		log_out
		redirect_to :back
	end

end

jcrew_app/app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

	def logged_in?
		!current_user.nil?
	end

	def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

jcrew_app/app/views/session/login.html.erb
<% if flash[:warning] && flash[:warning].count > 0 %>
    <div class="warning", style="background-color: transparent; color: rgba(92,211,173, 0.65);"><%= safe_join(flash[:warning], "<br>".html_safe) %></div>
    <br>
<% end %>
<div class="login-div" style="margin: 0em auto">
    <%= form_for :login, :url => login_user_path do |f| %>
    	<%= f.email_field :email, class: "login-input", placeholder: "Enter your email", style: "float:left;background-color: transparent;color:white;margin-top: 0.5em;" %>
    	<%= f.password_field :password, class: "login-input", placeholder: "Enter your password", style: "float:left;background-color: transparent;color:white;margin-top: 0.5em;" %>
    	<%= f.submit "Log in", class: "login-button", style: "margin-top: 0.5em;" %>
  	<% end %>
  	<br>
  	<p id="login-p">New User? <%= link_to 'Register', register_url, style:"color: rgba(92,211,173, 0.65);text-decoration: underline" %></p>
</div>

jcrew_app/app/views/session/register.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="warning" style="background-color: transparent; color: rgba(92,211,173, 0.65);list-style-type: none;"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="login-div" style="margin: 0em auto">
    <%= form_for :register, :url => register_user_path do |f| %>
     <%= f.email_field :email, class: "login-input", placeholder: "Enter your email", style: "float:left;background-color: transparent;color:white;margin-top: 0.5em;" %>
     <%= f.password_field :password, class: "login-input", placeholder: "Create a new password", style: "float:left;background-color: transparent;color:white;margin-top: 0.5em;" %>
     <%= f.text_field :name, class: "login-input", placeholder: "Enter your name", style: "float:left;background-color: transparent;color:white;margin-top: 0.5em;" %>
     <%= f.submit "Register", class: "login-button", style: "margin-top: 0.5em;" %>
     <% end %>
     <br>
     <p id="login-p">Already have an account? <%= link_to 'Log in', login_url, style:"color: rgba(92,211,173, 0.65);text-decoration: underline" %></p>
</div>